proxies:
  - name: "泰国-ISP节点"
    type: socks5
    server: 112.143.3.124
    port: 50101
    username: wup33772
    password: 7RdGm74iVb

proxy-groups:
  - name: 自动选择
    type: select
    proxies:
      - 泰国-ISP节点

rules:
  - MATCH,自动选择
